//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA_EQUIVALENCIAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EQUIVALENCIAEntities : DbContext
    {
        public EQUIVALENCIAEntities()
            : base("name=EQUIVALENCIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<CURSO> CURSO { get; set; }
        public virtual DbSet<EQUIVALENCIA> EQUIVALENCIA { get; set; }
        public virtual DbSet<EQUIVALENCIA_CURSO> EQUIVALENCIA_CURSO { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<ESTUDIANTE> ESTUDIANTE { get; set; }
        public virtual DbSet<SEDE> SEDE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
