//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA_EQUIVALENCIAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIVALENCIA_CURSO
    {
        public int ID_EQUIVALENCIA_CURSO { get; set; }
        public Nullable<int> ID_CURSO { get; set; }
        public Nullable<int> ID_EQUIVALENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual EQUIVALENCIA EQUIVALENCIA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
