//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA_EQUIVALENCIAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIVALENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIVALENCIA()
        {
            this.EQUIVALENCIA_CURSO = new HashSet<EQUIVALENCIA_CURSO>();
        }
    
        public int ID_EQUIVALENCIA { get; set; }
        public Nullable<int> NO_CARNET { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<System.DateTime> FECHA_EQUIVALENCIA { get; set; }
        public string LUGAR_FISICO { get; set; }
        public string OBSERVACIONES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIVALENCIA_CURSO> EQUIVALENCIA_CURSO { get; set; }
        public virtual SEDE SEDE { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
    }
}
